### ISSUE TITLE
redesign: cannot use SyntaxOrTermWrapper's val()?

### ISSUE THREAD

**Issue by tycho01** [mozilla/sweet.js#509]
I tried the following:
```
syntax test = function (ctx) {
  let expr = ctx.next().value;
  let v = expr.val();
  console.log('v', v);
  return #`${v}`;
}
test 1
```

Expected result: I can get the `val()` of something and use it within the macro.
Actual result: it returns Nothing.

**Comment by disnet** [comment]
Should work now.

**Comment by tycho01** [comment]
With `test ['foo', 'bar']` it appears `.val()` is now returning `null`.

**Comment by disnet** [comment]
That's intentional. I'm writing up the documentation on this but the key idea is that `['foo', 'bar']` is a single syntax object and so asking for its value doesn't make sense.

**Comment by tycho01** [comment]
Hmm, I see... My expectation was that its value would be, well, the array `['foo', 'bar']`. I'll definitely be reading as docs progress; looks like I'll definitely still have some learning to do.

**Comment by disnet** [comment]
You can get the syntax inside a delimiter with `.inner`.
